"""
Signals routes — pending signal queue management.
Signals are generated by the strategy runner and queued here
for manual confirmation (approve/reject) or auto-execution.
"""

import uuid
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from api.signal_bus import bus

router = APIRouter()


class Signal(BaseModel):
    symbol: str
    direction: str          # "BUY" or "SELL"
    trading_mode: str       # "scalping" | "day_trading" | "swing"
    strategy: str
    entry_price: float
    sl: float
    tp: Optional[float] = None
    lot_size: Optional[float] = None
    confidence: Optional[float] = None
    timeframe: str = ""
    note: Optional[str] = None


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/")
def list_signals(trading_mode: Optional[str] = None, status: Optional[str] = None):
    """Return signals, optionally filtered by trading_mode and/or status."""
    signals = list(bus.queue.values())
    if trading_mode:
        signals = [s for s in signals if s.get("trading_mode") == trading_mode]
    if status:
        signals = [s for s in signals if s.get("status") == status]
    return signals


@router.get("/{signal_id}")
def get_signal(signal_id: str):
    """Return a single signal by ID."""
    signal = bus.queue.get(signal_id)
    if not signal:
        raise HTTPException(status_code=404, detail="Signal not found")
    return signal


@router.post("/")
async def add_signal(signal: Signal):
    """
    Add a new signal to the queue.
    If execution_mode is 'auto' for this trading_mode, executes immediately.
    """
    signal_id = str(uuid.uuid4())
    entry = {
        "id":           signal_id,
        "created_at":   datetime.now(tz=timezone.utc).isoformat(),
        **signal.model_dump(),
    }
    return await bus.add_signal(entry)


@router.post("/{signal_id}/approve")
async def approve_signal(signal_id: str):
    """
    Manually approve a signal — places the order immediately.
    """
    signal = bus.queue.get(signal_id)
    if not signal:
        raise HTTPException(status_code=404, detail="Signal not found")
    if signal["status"] not in ("pending",):
        raise HTTPException(status_code=400, detail=f"Signal is already '{signal['status']}'")
    try:
        return await bus.execute_signal(signal_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Signal not found")


@router.post("/{signal_id}/reject")
def reject_signal(signal_id: str):
    """Reject and remove a signal from the queue."""
    signal = bus.queue.get(signal_id)
    if not signal:
        raise HTTPException(status_code=404, detail="Signal not found")
    signal["status"] = "rejected"
    signal["actioned_at"] = datetime.now(tz=timezone.utc).isoformat()
    bus.queue.pop(signal_id, None)
    return {"status": "rejected", "id": signal_id}


@router.delete("/{signal_id}")
def delete_signal(signal_id: str):
    """Permanently remove a signal from the queue (any status)."""
    if signal_id not in bus.queue:
        raise HTTPException(status_code=404, detail="Signal not found")
    bus.queue.pop(signal_id, None)
    return {"status": "deleted", "id": signal_id}


@router.delete("/")
def clear_signals(trading_mode: Optional[str] = None):
    """
    Remove signals from the queue.
    - trading_mode param: removes ALL signals for that specific mode.
    - No param: removes only terminal-state signals (executed/rejected/failed).
    """
    if trading_mode:
        to_remove = [k for k, v in bus.queue.items() if v.get("trading_mode") == trading_mode]
        for k in to_remove:
            bus.queue.pop(k, None)
        return {"status": "cleared", "removed": len(to_remove)}
    removed = _purge_all_terminal()
    return {"status": "ok", "removed": removed}


def _purge_all_terminal() -> int:
    terminal = frozenset({"executed", "rejected", "failed"})
    ids = [sid for sid, s in bus.queue.items() if s.get("status") in terminal]
    for sid in ids:
        bus.queue.pop(sid, None)
    return len(ids)
