"""
Signals routes — pending signal queue management.
Signals are generated by the strategy runner and queued here
for manual confirmation (approve/reject) or auto-execution.
"""

import asyncio
import uuid
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel
from slowapi import Limiter
from slowapi.util import get_remote_address

from api.signal_bus import bus

router = APIRouter()
limiter = Limiter(key_func=get_remote_address)
# Lock to prevent two simultaneous approve requests from placing duplicate orders.
# asyncio.Lock — correct for async endpoints; threading.Lock would block the event loop.
_approve_lock = asyncio.Lock()


def _sanitize_value(v):
    """Convert numpy scalar types to native Python types for JSON serialization."""
    if hasattr(v, "item"):  # numpy scalars expose .item()
        return v.item()
    if isinstance(v, dict):
        return {k2: _sanitize_value(v2) for k2, v2 in v.items()}
    return v


def _sanitize_dict(signal: dict) -> dict:
    return {k: _sanitize_value(v) for k, v in signal.items()}


def _sanitize(signals: list) -> list:
    return [_sanitize_dict(s) for s in signals]


class Signal(BaseModel):
    symbol: str
    direction: str          # "BUY" or "SELL"
    trading_mode: str       # "scalping" | "day_trading" | "swing"
    strategy: str
    entry_price: float
    sl: float
    tp: Optional[float] = None
    lot_size: Optional[float] = None
    confidence: Optional[float] = None
    timeframe: str = ""
    note: Optional[str] = None


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/archive")
@limiter.limit("100/minute")  # Task #7: Rate limiting
def get_archive(request: Request, limit: int = 100):
    """Return the last N completed/expired/rejected signals (G-5: signal archive)."""
    items = list(bus.archive)[-limit:]
    items.reverse()   # newest first
    return items


@router.get("/")
@limiter.limit("100/minute")  # Task #7: Rate limiting
def list_signals(request: Request, trading_mode: Optional[str] = None, status: Optional[str] = None):
    """Return signals, optionally filtered by trading_mode and/or status."""
    signals = list(bus.queue.values())
    if trading_mode:
        signals = [s for s in signals if s.get("trading_mode") == trading_mode]
    if status:
        signals = [s for s in signals if s.get("status") == status]
    return _sanitize(signals)


@router.get("/{signal_id}")
@limiter.limit("100/minute")  # Task #7: Rate limiting
def get_signal(request: Request, signal_id: str):
    """Return a single signal by ID."""
    signal = bus.queue.get(signal_id)
    if not signal:
        raise HTTPException(status_code=404, detail="Signal not found")
    return _sanitize_dict(signal)


@router.post("/")
@limiter.limit("50/minute")  # Task #7: Rate limiting (write endpoint - stricter)
async def add_signal(request: Request, signal: Signal):
    """
    Add a new signal to the queue.
    If execution_mode is 'auto' for this trading_mode, executes immediately.
    """
    signal_id = str(uuid.uuid4())
    entry = {
        "id":           signal_id,
        "created_at":   datetime.now(tz=timezone.utc).isoformat(),
        **signal.model_dump(),
    }
    return await bus.add_signal(entry)


@router.post("/{signal_id}/approve")
@limiter.limit("50/minute")  # Task #7: Rate limiting (write endpoint - stricter)
async def approve_signal(request: Request, signal_id: str):
    """
    Manually approve a signal — places the order immediately.
    Rejects with 410 if the signal has passed its expiry window.
    """
    # Acquire the lock atomically so two concurrent requests cannot both pass
    # the "pending" check and place duplicate orders.
    async with _approve_lock:
        signal = bus.queue.get(signal_id)
        if not signal:
            raise HTTPException(status_code=404, detail="Signal not found")
        if signal["status"] not in ("pending",):
            raise HTTPException(status_code=400, detail=f"Signal is already '{signal['status']}'")
        # Mark as executing inside the lock so any second request sees the new status
        signal["status"] = "executing"

    # Expiry check (done outside lock — just reverting status on fail is safe here)
    if signal.get("expires_at"):
        try:
            exp = datetime.fromisoformat(signal["expires_at"].replace("Z", "+00:00"))
            if datetime.now(tz=timezone.utc) >= exp:
                signal["status"] = "expired"
                signal["rejection_reason"] = "Signal expired — market conditions may have changed"
                raise HTTPException(
                    status_code=410,
                    detail={
                        "error": "signal_expired",
                        "message": "This signal has expired. Market conditions at time of signal may no longer be valid.",
                    },
                )
        except HTTPException:
            raise
        except Exception:
            pass
    try:
        return await bus.execute_signal(signal_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Signal not found")


class RejectRequest(BaseModel):
    reason: Optional[str] = None


@router.post("/{signal_id}/reject")
async def reject_signal(signal_id: str, body: RejectRequest = RejectRequest()):
    """Reject and remove a signal from the queue."""
    signal = bus.queue.get(signal_id)
    if not signal:
        raise HTTPException(status_code=404, detail="Signal not found")
    signal["status"] = "rejected"
    signal["actioned_at"] = datetime.now(tz=timezone.utc).isoformat()
    if body.reason:
        signal["rejection_reason"] = body.reason
    bus.queue.pop(signal_id, None)
    # Release dedup key so the next bar can generate a fresh signal for this
    # symbol/strategy/direction. Without this, the key stays locked until
    # purge_stale TTL (1 hr) — but purge_stale never sees the signal because
    # it was already removed from the queue here.
    _dk = (
        signal.get("symbol"), signal.get("strategy"),
        signal.get("direction"), signal.get("trading_mode"),
    )
    bus._pending_keys.discard(_dk)
    # GAP-1: sync persistent file when a swing auto-execute signal is rejected
    if signal.get("auto_execute_at"):
        bus._save_pending_swing_signals()
    # Broadcast rejection to dashboard so signal cards update in real time
    try:
        from api.websocket.feed import broadcast_signal
        asyncio.create_task(broadcast_signal({**signal, "type": "signal_update"}))
    except Exception:
        pass
    return {"status": "rejected", "id": signal_id}


@router.delete("/{signal_id}")
def delete_signal(signal_id: str):
    """Permanently remove a signal from the queue (any status)."""
    if signal_id not in bus.queue:
        raise HTTPException(status_code=404, detail="Signal not found")
    _sig = bus.queue.pop(signal_id, None)
    # GAP-1: sync persistent file when a swing auto-execute signal is deleted
    if _sig and _sig.get("auto_execute_at"):
        bus._save_pending_swing_signals()
    return {"status": "deleted", "id": signal_id}


@router.delete("/")
def clear_signals(trading_mode: Optional[str] = None):
    """
    Remove signals from the queue.
    - trading_mode param: removes ALL signals for that specific mode.
    - No param: removes only terminal-state signals (executed/rejected/failed).
    """
    if trading_mode:
        to_remove = [k for k, v in bus.queue.items() if v.get("trading_mode") == trading_mode]
        for k in to_remove:
            bus.queue.pop(k, None)
        return {"status": "cleared", "removed": len(to_remove)}
    removed = _purge_all_terminal()
    return {"status": "ok", "removed": removed}


def _purge_all_terminal() -> int:
    terminal = frozenset({"executed", "rejected", "failed", "expired"})
    ids = [sid for sid, s in bus.queue.items() if s.get("status") in terminal]
    for sid in ids:
        bus.queue.pop(sid, None)
    return len(ids)
