"""
Signals routes — pending signal queue management.
Signals are generated by the strategy runner and queued here
for manual confirmation (approve/reject) or auto-execution.
"""

import uuid
from datetime import datetime
from typing import Optional
from zoneinfo import ZoneInfo

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter()

# ---------------------------------------------------------------------------
# In-memory signal queue (replaced by DB in later phase)
# ---------------------------------------------------------------------------
_signal_queue: dict[str, dict] = {}


class Signal(BaseModel):
    symbol: str
    direction: str          # "BUY" or "SELL"
    trading_mode: str       # "scalping" | "day_trading" | "swing"
    strategy: str
    entry_price: float
    sl: float
    tp: Optional[float] = None
    confidence: Optional[float] = None
    timeframe: str
    note: Optional[str] = None


class SignalActionRequest(BaseModel):
    signal_id: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/")
def list_signals(trading_mode: Optional[str] = None):
    """Return all pending signals, optionally filtered by trading mode."""
    signals = list(_signal_queue.values())
    if trading_mode:
        signals = [s for s in signals if s["trading_mode"] == trading_mode]
    return signals


@router.get("/{signal_id}")
def get_signal(signal_id: str):
    """Return a single signal by ID."""
    signal = _signal_queue.get(signal_id)
    if not signal:
        raise HTTPException(status_code=404, detail="Signal not found")
    return signal


@router.post("/")
def add_signal(signal: Signal):
    """
    Add a new signal to the pending queue.
    Called by the strategy runner when a signal fires.
    """
    signal_id = str(uuid.uuid4())
    entry = {
        "id":           signal_id,
        "status":       "pending",
        "created_at":   datetime.now(tz=ZoneInfo("UTC")).isoformat(),
        **signal.model_dump(),
    }
    _signal_queue[signal_id] = entry
    return entry


@router.post("/{signal_id}/approve")
def approve_signal(signal_id: str):
    """
    Mark a signal as approved for execution.
    The strategy runner polls this and fires the order.
    """
    signal = _signal_queue.get(signal_id)
    if not signal:
        raise HTTPException(status_code=404, detail="Signal not found")
    if signal["status"] != "pending":
        raise HTTPException(status_code=400, detail=f"Signal is already '{signal['status']}'")
    signal["status"] = "approved"
    signal["actioned_at"] = datetime.now(tz=ZoneInfo("UTC")).isoformat()
    return signal


@router.post("/{signal_id}/reject")
def reject_signal(signal_id: str):
    """Reject and remove a signal from the queue."""
    signal = _signal_queue.get(signal_id)
    if not signal:
        raise HTTPException(status_code=404, detail="Signal not found")
    signal["status"] = "rejected"
    signal["actioned_at"] = datetime.now(tz=ZoneInfo("UTC")).isoformat()
    # Remove from active queue after rejection
    _signal_queue.pop(signal_id, None)
    return {"status": "rejected", "id": signal_id}


@router.delete("/{signal_id}")
def delete_signal(signal_id: str):
    """Remove a signal from the queue (used after execution)."""
    if signal_id not in _signal_queue:
        raise HTTPException(status_code=404, detail="Signal not found")
    _signal_queue.pop(signal_id)
    return {"status": "deleted", "id": signal_id}


@router.delete("/")
def clear_signals(trading_mode: Optional[str] = None):
    """Clear all pending signals, optionally filtered by mode."""
    global _signal_queue
    if trading_mode:
        _signal_queue = {
            k: v for k, v in _signal_queue.items()
            if v["trading_mode"] != trading_mode
        }
    else:
        _signal_queue = {}
    return {"status": "cleared"}
